### ISSUE TITLE
Bug : URI malformed on first launch

### ISSUE THREAD

**Issue by codot-fr** [ExpressGateway/express-gateway#737]
Hello,

I just don't get it. I got through the initial 4-step setup quite easily but then on first launch. What the fork? Sorry, I'm missing something big, but I just don't see it.

Thanks

npm start

> infapigw@1.0.0 start /root/infapigw
> node server.js

url.js:289
      this.auth = decodeURIComponent(rest.slice(0, atSign));
                  ^

URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at Url.parse (url.js:289:19)
    at Object.urlParse [as parse] (url.js:97:13)
    at mapOptsToProxy (/root/infapigw/node_modules/proxy-agent/index.js:88:43)
    at new ProxyAgent (/root/infapigw/node_modules/proxy-agent/index.js:150:17)
    at module.exports (/root/infapigw/node_modules/express-gateway/lib/policies/proxy/proxy.js:52:26)
    at policy.policy.args (/root/infapigw/node_modules/express-gateway/lib/policies/index.js:30:16)
    at pipelinePoliciesConfig.forEach.policyConfig (/root/infapigw/node_modules/express-gateway/lib/gateway/pipelines.js:134:32)
    at Array.forEach (<anonymous>)
    at configurePipeline (/root/infapigw/node_modules/express-gateway/lib/gateway/pipelines.js:112:26)
    at Object.module.exports.bootstrap (/root/infapigw/node_modules/express-gateway/lib/gateway/pipelines.js:19:20)
    at bootstrap (/root/infapigw/node_modules/express-gateway/lib/gateway/index.js:91:26)
    at module.exports (/root/infapigw/node_modules/express-gateway/lib/gateway/index.js:20:39)
    at Main.run (/root/infapigw/node_modules/express-gateway/lib/index.js:23:43)
    at Object.<anonymous> (/root/infapigw/server.js:6:4)
    at Module._compile (module.js:652:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! infapigw@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the infapigw@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-24T15_58_40_912Z-debug.log

[2018-05-24T15_58_40_912Z-debug.log](https://github.com/ExpressGateway/express-gateway/files/2038357/2018-05-24T15_58_40_912Z-debug.log)

**Comment by XVincentX** [comment]
Hey — this seems to be something with your `gateway.config` file. If you could paste it here, I could have a look into and eventually output a better error message for such thing.

I'll close this issue; feel free to keep commenting on this anyway.

**Comment by codot-fr** [comment]
Here you go. Haven't touched it since the setup.

http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true

**Comment by XVincentX** [comment]
I can run the gateway correctly with such file.

What NodeJS version are you using? Can you paste the output of `node -v` and `npm -v`

Also — why don't you jump on our [Gitter](https://gitter.im/ExpressGateway/express-gateway) channel? It's going to be easier to help you.

**Comment by codot-fr** [comment]
`[root@wqya0010 config]# node -v
v8.11.2
[root@wqya0010 config]# npm -v
5.6.0
`

**Comment by XVincentX** [comment]
Please jump on out Gitter channel, it's going to be easier to help you from there.

**Comment by XVincentX** [comment]
It turns out this is because of an invalid value for env variable for http proxy
