### ISSUE TITLE
1.6.1 breaks regexpmatch condition with express-gateway-plugin-rewrite plugin

### ISSUE THREAD

**Issue by AnsonT** [ExpressGateway/express-gateway#898]
.../node_modules/express-gateway/lib/gateway/pipelines.js:152
        middlewares = conditionDefinitions.find(cd => cd.name === conditionConfig.name).middlewares;
                                                                                       ^

TypeError: Cannot read property 'middlewares' of undefined
    at policyStep (/src/GoDaddy/product-integration-platform/pip-api-gateway/node_modules/express-gateway/lib/gateway/pipelines.js:152:88)
    at arrayMap (/src/GoDaddy/product-integration-platform/pip-api-gateway/node_modules/lodash.flatmap/index.js:140:21)
    at map (/src/GoDaddy/product-integration-platform/pip-api-gateway/node_modules/lodash.flatmap/index.js:1928:10)
    at flatMap (/src/GoDaddy/product-integration-platform/pip-api-gateway/node_modules/lodash.flatmap/index.js:1881:22)
    at pipelinePoliciesConfig.forEach.policyConfig (/src/GoDaddy/product-integration-platform/pip-api-gateway/node_modules/express-gateway/lib/gateway/pipelines.js:144:25)
    at Array.forEach (<anonymous>)
    at configurePipeline (/src/GoDaddy/product-integration-platform/pip-api-gateway/node_modules/express-gateway/lib/gateway/pipelines.js:128:26)
    at Object.module.exports.bootstrap (/src/GoDaddy/product-integration-platform/pip-api-gateway/node_modules/express-gateway/lib/gateway/pipelines.js:23:20)
    at bootstrap (/src/GoDaddy/product-integration-platform/pip-api-gateway/node_modules/express-gateway/lib/gateway/index.js:80:26)
    at module.exports (/src/GoDaddy/product-integration-platform/pip-api-gateway/node_modules/express-gateway/lib/gateway/index.js:20:39)

Reverting to 1.6.0 does not cause this error

**Comment by XVincentX** [comment]
Fixed in 1.6.2 — it was a bad release.

P.S: @AnsonT It's great to see GoDaddy use EG in production. Can we talk?

**Comment by AnsonT** [comment]
@XVincentX reach me at ansont@ gd. We are just evaluating EG at the moment, not production yet.
